ASKEducation/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;

namespace ASKEducation.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: /Article/

        public ActionResult Index()
        {
            MySqlConnection Connection = new MySqlConnection("Database=u0066974_ask_education;Data Source=37.140.192.132;User Id=u0066_root;Password=gEt7m29&");

            string blogListQuery = @"SELECT * FROM blog ORDER BY date_stamp desc";

            MySqlCommand blogListCom = new MySqlCommand(blogListQuery, Connection);

            DataTable blogList = new DataTable();

            using (Connection)
            {
                Connection.Open();

                using (MySqlDataReader dr2 = blogListCom.ExecuteReader())
                {
                    if (dr2.HasRows)
                    {
                        try
                        {
                            blogList.Load(dr2);
                        }
                        catch (Exception e)
                        {
                        }

                    }
                }
            }

            ViewBag.blogList = blogList;

            return View();
        }

        public ActionResult Item(int id)
        {
            MySqlConnection Connection = new MySqlConnection("Database=u0066974_ask_education;Data Source=37.140.192.132;User Id=u0066_root;Password=gEt7m29&");

            string sSQL = @"SELECT * FROM blog where id=" + id;


            DataTable dt = new DataTable();

            using (Connection)
            {
                Connection.Open();

                MySqlCommand com = new MySqlCommand(sSQL, Connection);

                using (MySqlDataReader dr = com.ExecuteReader())
                {
                    if (dr.HasRows)
                    {
                        try
                        {
                            dt.Load(dr);
                        }
                        catch (Exception e) { }

                    }
                }


            }

            ViewBag._blog = dt;
            return View();
        }

    }
}

ASKEducation/Views/Article/Index.cshtml
@using System.Data
@{
    DataTable blogList = ViewBag.blogList;
    ViewBag.Title = "Статьи обучение за рубежом";
    ViewBag.MetaKeywords = "askeducation - образование, обучение, учеба за рубежом и за границей";
    ViewBag.MetaDescription = "askeducation - команда профессионалов, которая проводит подбор и бронирование программ обучения за рубежом. Почитайте наши статьи.";
}

<div class="s-container">
    <div>
        <ul class="s-breadcrumbs clear s-mt_18">
            <li class="s-breadcrumbs-item">
                <a class="s-mr_10" href="/">Главная</a>
                <i class="fa fa-angle-right s-c_777 s-fs_14"></i>
            </li>
            <li class="s-breadcrumbs-item">
                <a href="@Request.Url.AbsoluteUri">Статьи</a>
            </li>
        </ul>
    </div>
    <h1>Статьи</h1>
    <div class="row">
        @foreach (DataRow item in blogList.Rows)
        {

            if ((System.Boolean)item["isBlog"] == false)
            {
                <div class="b-blog col-md-12 col-lg-12 col-sm-12 s-mb_18">
                    <p>
                        <a href="~/Article/item/@item["id"]">
                            <strong>
                                <span>@item["date"]</span>&nbsp;
                                <span>@item["name"]</span>
                            </strong>
                        </a>
                    </p>
                    <div class="row s-mb_18">
                        @{ var imgName = item["id"] + ".jpg"; }
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 s-ta_c s-mb_18">
                            <img alt="@item["name"]" title="@item["name"]" class="s-full s-max-210" src="~/Content/images/blog/@imgName" />
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">@item["description"]</div>
                    </div>
                </div>


            }
        }

    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Content/js/models/blogModel.js"></script>
}

ASKEducation/Views/Article/Item.cshtml
@using System.Data
@{
    DataTable blogCurrent = ViewBag._blog;
    ViewBag.blog = blogCurrent.Rows[0];
    ViewBag.MetaDescription = blogCurrent.Rows[0]["meta_description"];
    ViewBag.MetaKeywords = blogCurrent.Rows[0]["meta_keywords"];
    //ViewBag.Title = blogCurrent.Rows[0]["title"];
    ViewBag.Title = blogCurrent.Rows[0]["name"];
    string imageUrl = "/Content/images/blog/" + blogCurrent.Rows[0]["id"] + ".jpg";
}

<div class="s-container">
    <div>
        <ul class="s-breadcrumbs clear s-mt_18">
            <li class="s-breadcrumbs-item">
                <a class="s-mr_10" href="/">Главная</a>
                <i class="fa fa-angle-right s-c_777 s-fs_14"></i>
            </li>
            <li class="s-breadcrumbs-item">
                <a class="s-mr_10" href="@Url.Action("index", "Article")">статьи</a>
                <i class="fa fa-angle-right s-fs_14"></i>
            </li>
            <li class="s-breadcrumbs-item">
                <a href="@Request.Url.AbsoluteUri">@ViewBag.Title</a>
            </li>
        </ul>
    </div>
    <h1>
        <span>@blogCurrent.Rows[0]["date"]</span>
        <span>@ViewBag.Title</span>
    </h1>
    <div class="s-line _grey"></div>
    <div class="row">
        <!--<div class="col-lg-3 col-md-3 col-sm-3 s-ta_c s-mb_18">
            <img data-bind="attr:{src:('/Content/images/blog/'+ blog.id() + '.jpg')}" width="200"/>
        </div>
        <div data-bind="html:blog.description_full" class="col-lg-9 col-md-9 col-sm-9 wysicontent s-fs_14 s-word_break"></div>-->
        <div class="col-lg-3 col-md-3 col-sm-3 s-ta_c s-mb_18">
            <img title="@ViewBag.Title" alt="@ViewBag.Title" src="@imageUrl" width="200" />
        </div>
        <div class="col-lg-9 col-md-9 col-sm-9 wysicontent s-fs_14 s-word_break">@Html.Raw(blogCurrent.Rows[0]["description_full"])</div>
        
    </div>
</div>

@section scripts{
    <script type="text/javascript" src="~/Content/js/models/blogPageModel.js?@DateTime.Now.GetHashCode()"></script>
    <script>
        BC.init(document.location.pathname.split("/").slice(-1));
    </script>
}